title: Making an in-app voice call
description: You make a voice call from an iOS app to a phone.
products:
  - client-sdk

introduction:
  title: Introduction to this task
  description: This task shows you how to use make a phone call from an iOS app using the iOS Client SDK and Swift.
  content: |
    # Introduction
    In this tutorial, you will learn how to create an iOS application using Swift and the Nexmo iOS Client SDK, and then write the code to make a phone call from your iOS app to a phone.

    ### Completed project
    If you would like to follow along without building the app yourself, the completed project for this tutorial is available on [Github](https://github.com/nexmo-community/client-sdk-swift-voice-app-to-phone) for you to download.

prerequisites:
- create-nexmo-account
- install-nodejs
- install-nexmo-cli-beta
- install-xcode
- join-github

tasks:
- client-sdk/app-to-phone/create-ncco
- client-sdk/app-to-phone/create-application
- client-sdk/create-user
- client-sdk/generate-jwt-alice
- client-sdk/app-to-phone/project
- client-sdk/app-to-phone/permissions
- client-sdk/app-to-phone/interface
- client-sdk/app-to-phone/client
- client-sdk/app-to-phone/call

conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?

    For completeness, the project you've built as part of this tutorial is also available on [Github](https://github.com/nexmo-community/client-sdk-swift-voice-app-to-phone).

    And... you can do a lot more with the Client SDK.

    We want to hear what ideas you have in mind? Contact us at [devrel@vonage.com](mailto:devrel@vonage.com)

    See [Client SDK documentation](/client-sdk/overview).
